version: "3.8"
services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.4
    container_name: keycloak
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    command:
      - "start-dev"
      - "--http-relative-path /auth"
      - "--spi-theme-static-max-age=-1 --spi-theme-cache-themes=false --spi-theme-cache-templates=false"
    volumes:
      - ./dist_keycloak/keycloak-theme-for-kc-22-and-above.jar:/opt/keycloak/providers/keycloak-theme.jar
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      - "KEYCLOAK_ADMIN=admin"
      - "KEYCLOAK_ADMIN_PASSWORD=admin"
